[package]
name = "db_mysql"
version = "0.1.0"
authors = ["vladgon <valdgon@gmail.com>"]
edition = "2021"

[dependencies]
util = { path = "../util" }
dotenv = "0.15.0"
config = { version = "0.13.4" }
serde = { version = "1.0.194", features = ["derive"] }