[package]
name = "db_diesel"
version = "0.1.0"
authors = ["vladgon <valdgon@gmail.com>"]
edition = "2018"

[dependencies]
util = {path = "../util"}
diesel = { version = "^1.4.3", features = ["mysql"] }
dotenv = "0.14.1"