[package]
name = "db_diesel"
version = "0.1.0"
authors = ["vladgon <valdgon@gmail.com>"]
edition = "2021"

[dependencies]
diesel = { workspace = true, features = ["mysql"] }
wg_util = { workspace = true }
log = { workspace = true }

[dev-dependencies]
ctor = "0.2.6"
