[package]
name = "web_server"
version = "0.1.0"
authors = ["vladgon <valdgon@gmail.com>"]
edition = "2018"

[dependencies]
tokio={version="^0.2", features=["rt-core","rt-threaded","macros", "blocking","stream", "time"]}
futures="0.3.5"
tracing = "^0.1"
tracing-subscriber = "0.2.5"
tracing-futures="0.2.4"