[package]
name = "wg_sample_app"
version = "0.1.0"
edition = "2021"

[dependencies]
wg_util = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
wg_util = { workspace = true }