[package]
name = "wg_sample_app"
version = "0.1.0"
edition = "2021"

[dependencies]
wg_util = { path = "../wg_util" }
anyhow = "1"
log = "0"

[build-dependencies]
anyhow = "1"
wg_util = { path = "../wg_util" }