[package]
name = "webui"
version = "0.1.0"
authors = ["vladgon <valdgon@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "~0.4"
serde = {version = "^1.0", features = ["derive"]}
enclose = "~1.1.0"

[build-dependencies]
minifier="~0.0.33"